[project]
name = "sqoo"
version = "0.13.0"
description = ""
authors = [
    {name = "SergioZSZ",email = "s.zaballosh@gmail.com"}
]
license = "Apache-2.0"
requires-python = ">=3.11, <3.13"
dependencies = []


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
soca = {path = "containers/soca_container/soca", develop = true}
rsfc = {path = "containers/rsfc_container/rsfc-0.1.7", develop = true}
resqui = {path = "containers/resqui_container/QualityPipelines-2.0", develop = true}

