

services:

  n8n:
    build: ./n8n_container
    container_name: n8n
    user: root
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_container/n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - .//outputs:/root/.n8n-files
    depends_on:
      - rabbitmq
    networks:
      - net
    group_add:
      - "998"
    environment:
      # *** Privadas ***
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - OUTPUTS=${OUTPUTS}
      # *** General ***
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      # *** Settings ***
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODES_EXCLUDE=[]
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_USER_FOLDER=/home/node/.n8n
      # *** RabbitMQ ***
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RATE_LIMIT_RSFC_ENABLED=${RATE_LIMIT_RSFC_ENABLED}

  worker_soca:
    build:
      context: ./soca_container
    command: python -u -m soca_runner.worker
    volumes:
      - ./outputs:/app/outputs
    networks:
      - net
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

    


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit consumer_timeout 7200000"
    networks:
    - net


  worker_rsfc:
    build:
      context: ./rsfc_container
    command: python -u -m rsfc_runner.worker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net
    volumes:
      - ./outputs:/app/outputs
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}


  rate_limiter_rsfc:
    build:
      context: ./rsfc_container
    command: python -m rsfc_runner.rabbitmq.rate_limiter
    depends_on:
      - rabbitmq
    environment:
      - DATABASE_URL=${DATABASE_URL}  
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RATE_LIMIT_RSFC_ENABLED=${RATE_LIMIT_RSFC_ENABLED}

    networks:
      - net

  rate_limiter_soca:
    build:
      context: ./soca_container
    command: python -m soca_runner.rabbitmq.rate_limiter
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RATE_LIMIT_SOCA_ENABLED=${RATE_LIMIT_SOCA_ENABLED}
    networks:
      - net


  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rsfc"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: postgres_rsfc
    environment:
      POSTGRES_USER: rsfc
      POSTGRES_PASSWORD: rsfc
      POSTGRES_DB: jobs

    networks:
      - net
    ports:
      - "5432:5432"




networks:
  net:
    driver: bridge