slice_name: Total Assessments
description: Total quality assessments submitted across all software.
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  metric:
    label: assessments
    expressionType: SIMPLE
    column:
      column_name: assessment_id
    aggregate: COUNT_DISTINCT
  header_font_size: 0.25
  subheader_font_size: 0.1
  subheader: Assessments Completed
  color_picker:
    r: 0
    g: 114
    b: 178
    a: 1
  number_format: ',d'
  viz_type: big_number_total
query_context: null
cache_timeout: null
uuid: 04a5f0a9-87de-4262-a4c9-19eb93052c5a
version: 1.0.0
dataset_uuid: 9ccd1028-35e4-4b23-9d3b-178fac4ed156
