slice_name: Total Indicators
description: Number of indicators in the EVERSE catalog.
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  metric:
    label: count
    expressionType: SQL
    sqlExpression: COUNT(*)
  header_font_size: 0.25
  subheader_font_size: 0.1
  subheader: Catalog Indicators
  color_picker:
    r: 110
    g: 110
    b: 120
    a: 1
  number_format: ',d'
query_context: null
cache_timeout: null
uuid: b4ecc26c-934d-4db7-87fb-be0573af76e4
version: 1.0.0
dataset_uuid: eacc0b0c-6e6c-4c75-84c2-115ef1ffc527
