slice_name: Tools Coverage
description: Number of distinct tools active in the assessments in scope.
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  groupbyRows:
  - tool_name
  - dimension_name
  - indicator_name
  groupbyColumns: []
  metrics:
  - label: ' '
    expressionType: SIMPLE
    column:
      column_name: assessment_id
    aggregate: COUNT
  adhoc_filters:
  - clause: WHERE
    expressionType: SIMPLE
    subject: tool_name
    operator: IS NOT NULL
    comparator: ''
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  aggregateFunction: Sum
  valueFormat: ' '
  date_format: smart_date
  row_limit: 10000
  rowSubtotalPosition: false
  colSubtotalPosition: false
  rowTotals: false
  colTotals: false
  combineMetric: true
  conditional_formatting: []
query_context: null
cache_timeout: null
uuid: 78464b78-070b-4344-982f-e4266715edc7
version: 1.0.0
dataset_uuid: 9ccd1028-35e4-4b23-9d3b-178fac4ed156
